/* Codice di base che userò per creare delle tabella da immettere in SupaBase */
drop table if exists theorems_list; 

create table theorems_list(
	id BIGINT generated by default as identity primary key,
  corrAns text,
  enunciato text,
  dimostrazione text
); 

/* Saranno presenti 30 teoremi, di cui un paio circa saranno dei soli veri o falso */

insert into theorems_list(enunciato, corrAns, dimostrazione)
values 
(
$$Ogni successione convergente \`e limitata$$,
$$Vero$$,
$$Sia $(a_n)_{n\in\mathbb{N}}$ una successione di numeri reali e supponiamo che $a_n \to \ell$ per $n \to +\infty$, dove $\ell \in \mathbb{R}$. Dobbiamo provare che si pu\`o scegliere un $C > 0$ in modo che
\[
  \forall\, n \in \mathbb{N}\colon\; |a_n| \leq C.
\]
Allora, dato che $a_n \to \ell$ per $n \to +\infty$, dalla definizione di limite segue che in corrispondenza di $\varepsilon = 1$ \`e possibile trovare $\nu \in \mathbb{N}$ tale che
\[
  \forall\, n \in \mathbb{N},\, n > \nu\colon\; |a_n - \ell| < 1.
\]
Ora, dalla disuguaglianza triangolare risulta che per ogni intero $n > \nu$,
\[
  |a_n| = |a_n - \ell + \ell| \leq |a_n - \ell| + |\ell| < 1 + |\ell|.
\]
Quindi se considero la successione dei valori assoluti dei termini della successione, la situazione \`e la seguente
\[
  |a_0|,\; |a_1|,\; |a_2|,\;\ldots,\; |a_\nu|,\;
  \underbrace{|a_{\nu+1}|,\; |a_{\nu+2}|,\;\cdots}_{\text{questi termini sono} < 1+|\ell|}.
\]
Perci\`o, posto
\[
  C = \max\{|a_0|, \ldots, |a_\nu|, 1+|\ell|\} \in \mathbb{R},
\]
si ha che
\[
  \forall\, n \in \mathbb{N}\colon\;
  \begin{cases}
    \text{se } n \leq \nu, \text{ allora } |a_n| \leq C \\
    \text{se } n > \nu, \text{ allora } |a_n| < 1+|\ell| \leq C.
  \end{cases}
\]
Quindi in ogni caso, per ogni $n \in \mathbb{N}$, $|a_n| \leq C$ e perci\`o la successione \`e limitata.$$
),


/*Permanenza delle disuguaglianze*/
(
$$Sia $A \subset \mathbb{R}$ e $x_0 \in \overline{\mathbb{R}}$ un punto di accumulazione per $A$ in $\overline{\mathbb{R}}$. Siano $f\colon A \to \mathbb{R}$ e $g\colon A \to \mathbb{R}$ due funzioni e supponiamo che
\[
  \lim_{x \to x_0} f(x) = \ell \in \overline{\mathbb{R}}
  \quad\text{e}\quad
  \lim_{x \to x_0} g(x) = m \in \overline{\mathbb{R}}.
\]
Allora
\[
  \ell > m \;\Rightarrow\; f(x) > g(x) \text{ in un intorno di } x_0.
\]$$, 
$$Permanenza delle disuguaglianze$$,
$$Per ipotesi $\ell, m \in \overline{\mathbb{R}}$ e $\ell > m$. Possiamo sicuramente scegliere due intorni $V_1$ e $V_2$, rispettivamente di $\ell$ e $m$ in modo che
\[
  V_1 \cap V_2 = \varnothing \quad\text{e}\quad V_1 \geq V_2 \text{ (sono separati)}.
\]
In altre termini si ha
\begin{equation}
  \forall\, y_1 \in V_1,\, \forall\, y_2 \in V_2\colon\quad y_1 > y_2. \label{eq:perm1}
\end{equation}
Allora, dato che per ipotesi $f(x) \to \ell$ e $g(x) \to m$ per $x \to x_0$, si deve avere
\[
  f(x) \in V_1 \text{ in un intorno di } x_0 \quad\text{e}\quad g(x) \in V_2 \text{ in un intorno di } x_0.
\]
Allora risulta che
\[
  f(x) \in V_1 \text{ e } g(x) \in V_2 \text{ simultaneamente in un intorno di } x_0
\]
e quindi, per la \eqref{eq:perm1}, che
\[
  f(x) > g(x) \text{ in un intorno di } x_0.
  \qedhere
\]$$
),

/*Prolungamento delle disuguaglianze*/
(
$$Sia $A \subset \mathbb{R}$ e $x_0 \in \overline{\mathbb{R}}$ un punto di accumulazione per $A$ in $\overline{\mathbb{R}}$. Siano $f\colon A \to \mathbb{R}$ e $g\colon A \to \mathbb{R}$ due funzioni e supponiamo che $\lim_{x \to x_0} f(x) = \ell$ e $\lim_{x \to x_0} g(x) = m$. Allora
\[
  f(x) \leq g(x) \text{ in un intorno di } x_0 \;\Rightarrow\; \ell \leq m.
\]$$,
$$Vero$$,
$$Supponiamo che $f(x) \leq g(x)$ in un intorno di $x_0$. La dimostrazione procede per assurdo. Se fosse $\ell > m$, per il teorema della permanenza delle disuguaglianze (Teorema 1.1) si avrebbe
\[
  f(x) > g(x) \text{ in un intorno di } x_0.
\]
Ma stiamo supponendo che $f(x) \leq g(x)$ in un intorno di $x_0$ e quindi (prendendo come al solito l'intersezione degli intorni) si arriverebbe a
\[
  f(x) \leq g(x) \text{ e } f(x) > g(x) \text{ simultaneamente in un intorno di } x_0.
\]
E questo produce una contraddizione, dato che un numero reale non pu\`o essere simultaneamente minore o uguale e strettamente maggiore di un altro numero reale.$$
),

/*Teorema dei carabinieri*/
(
$$Sia $A \subset \mathbb{R}$ e $x_0 \in \overline{\mathbb{R}}$ un punto di accumulazione per $A$ in $\overline{\mathbb{R}}$. Siano $f$, $g$ e $h$ tre funzioni definite in $A$ a valori in $\mathbb{R}$ e supponiamo che
\begin{enumerate}[label=\alph*)]
  \item $f(x) \leq g(x) \leq h(x)$ in un intorno di $x_0$.
  \item $\lim_{x \to x_0} f(x) = \ell$ e $\lim_{x \to x_0} h(x) = \ell$ con $\ell \in \overline{\mathbb{R}}$.
\end{enumerate}
Allora $\lim_{x \to x_0} g(x) = \ell$.$$,
$$Teorema dei carabinieri (o del confronto)$$,
$$Sia $V$ un intorno di $\ell$. Si deve provare che $g(x) \in V$ in un intorno di $x_0$. Osserviamo preliminarmente che, essendo $V$ un intervallo di $\overline{\mathbb{R}}$, vale che
\begin{equation}
  y_1, y_2 \in V \text{ e } y_1 \leq y_2 \;\Rightarrow\; [y_1,y_2] \subset V. \label{eq:car2}
\end{equation}
Iniziamo ora la dimostrazione. Dall'ipotesi b) si ha
\[
  f(x) \in V \text{ in un intorno di } x_0 \quad\text{e}\quad h(x) \in V \text{ in un intorno di } x_0.
\]
Inoltre, per l'ipotesi a), si ha anche che
\[
  f(x) \leq g(x) \leq h(x) \text{ in un intorno di } x_0.
\]
Perci\`o, possiamo affermare che
\[
  \begin{cases}
    f(x) \in V \\
    h(x) \in V \\
    f(x) \leq g(x) \leq h(x)
  \end{cases}
  \quad\text{sono simultaneamente vere in un intorno di } x_0.
\]
Allora, ricordando la \eqref{eq:car2}, si pu\`o concludere che $g(x) \in V$ in un intorno di $x_0$.$$
),

/*Teorema degli Zeri di Bolzano*/
(
$$Sia $I$ un intervallo di $\mathbb{R}$ e $f\colon I \to \mathbb{R}$ continua. Siano $a, b \in I$ con $a < b$ e tali che $f(a)f(b) < 0$ (cio\`e $f(a)$ e $f(b)$ hanno segni discordi). Allora esiste $x_0 \in\; ]a,b[$ tale che $f(x_0) = 0$.$$,
$$Teorema degli Zeri di Bolzano$$,
$$Utilizzeremo un metodo iterativo chiamato \emph{metodo di bisezione} per produrre una successione di intervalli chiusi e limitati ciascuno contenuto nel precedente. Poniamo $I_0 = [a_0, b_0]$, dove $a_0 = a$ e $b_0 = b$. Controlliamo il punto medio dell'intervallo $c_0 = (a_0+b_0)/2$. Se $f(c_0) = 0$ abbiamo finito (perch\'e abbiamo trovato un punto in $]a,b[$ in cui la funzione si annulla). Altrimenti se $f(c_0) \neq 0$, essendo $f(a_0)$ e $f(b_0)$ con segni discordi, $f(c_0)$ sar\`a discorde con uno di essi. Scegliamo tra i sottointervalli $[a_0, c_0]$ e $[c_0, b_0]$ quello ai cui estremi la funzione ha segno discorde e chiamiamolo $I_1$. Poniamo cio\`e
\[
  I_1 = [a_1, b_1], \text{ dove }
  \begin{cases}
    a_1 = a_0,\; b_1 = c_0 & \text{se } f(a_0)f(c_0) < 0 \\
    a_1 = c_0,\; b_1 = b_0 & \text{se } f(c_0)f(b_0) < 0.
  \end{cases}
\]
Controlliamo il punto medio di $I_1$: $c_1 = (a_1+b_1)/2$. Se $f(c_1) = 0$ abbiamo finito. Altrimenti se $f(c_1) \neq 0$ scegliamo tra i sottointervalli $[a_1, c_1]$ e $[c_1, b_1]$ quello ai cui estremi la funzione ha valore di segno discorde e chiamiamolo $I_2$, cio\`e poniamo
\[
  I_2 = [a_2, b_2] \text{ dove }
  \begin{cases}
    a_2 = a_1,\; b_2 = c_1 & \text{se } f(a_1)f(c_1) < 0 \\
    a_2 = c_1,\; b_2 = b_1 & \text{se } f(c_1)f(b_1) < 0.
  \end{cases}
\]
Al passo $n$-esimo, se abbiamo definito $I_n = [a_n, b_n]$, controlliamo il punto medio di $I_n$: $c_n = (a_n + b_n)/2$. Se $f(c_n) = 0$ abbiamo finito. Altrimenti se $f(c_n) \neq 0$, definiamo
\[
  I_{n+1} = [a_{n+1}, b_{n+1}] \text{ dove }
  \begin{cases}
    a_{n+1} = a_n,\; b_{n+1} = c_n & \text{se } f(a_n)f(c_n) < 0 \\
    a_{n+1} = c_n,\; b_{n+1} = b_n & \text{se } f(c_n)f(b_n) < 0.
  \end{cases}
\]
\hrule\vspace{4pt}
In questo modo il procedimento termina dopo un certo numero di iterazioni, oppure continua indefinitamente e definisce una successione di intervalli chiusi e limitati $(I_n)_{n\in\mathbb{N}}$, $I_n = [a_n, b_n]$, con $I_0 = [a,b]$ e
\begin{equation}
  \forall\, n \in \mathbb{N}\colon\;
  \begin{cases}
    \underbrace{a_n \leq a_{n+1} \leq b_{n+1} \leq b_n}_{I_n} \\[4pt]
    b_{n+1} - a_{n+1} = \dfrac{b_n - a_n}{2} \\[4pt]
    f(a_n)f(b_n) < 0.
  \end{cases} \label{eq:bis1}
\end{equation}
Allora dalla prima delle \eqref{eq:bis1} si vede che la successione $(a_n)_{n\in\mathbb{N}}$ \`e crescente e la successione $(b_n)_{n\in\mathbb{N}}$ \`e decrescente. Inoltre sono entrambe limitate (perch\'e $a \leq a_n \leq b_n \leq b$). Perci\`o per il teorema sui limiti delle funzioni monotone sono entrambe convergenti. In particolare
\[
  a_n \to x_0 := \sup_{n\in\mathbb{N}} a_n \in [a,b]
  \quad\text{e}\quad
  b_n \to x_1 := \inf_{n\in\mathbb{N}} b_n \in [a,b].
\]
Poi, dalla seconda delle \eqref{eq:bis1} si ha
\begin{equation}
  b_n - a_n = \frac{b_{n-1}-a_{n-1}}{2} = \frac{b_{n-2}-a_{n-2}}{2^2}
  = \cdots = \frac{b-a}{2^n} \to 0. \label{eq:bis2}
\end{equation}
Ma d'altra parte $b_n - a_n \to x_1 - x_0$ e quindi $x_0 = x_1$, cio\`e le successioni $(a_n)_{n\in\mathbb{N}}$ e $(b_n)_{n\in\mathbb{N}}$ tendono allo stesso limite $x_0 = \sup_{n\in\mathbb{N}} a_n = \inf_{n\in\mathbb{N}} b_n$. Allora
\begin{equation}
  a_n \leq x_0 \leq b_n
  \quad\text{e}\quad
  \begin{cases}
    a_n \to x_0 \\
    b_n \to x_0.
  \end{cases} \label{eq:bis3}
\end{equation}
Pertanto, per la continuit\`a di $f$ (teorema ponte) si ha
\[
  \begin{cases}
    f(a_n) \to f(x_0) \\
    f(b_n) \to f(x_0)
  \end{cases}
  \;\Rightarrow\;
  \underbrace{f(a_n)f(b_n)}_{<0} \to f(x_0)^2
  \;\xRightarrow{\text{teo di prolungamento disuguaglianze}}\;
  f(x_0)^2 \leq 0 \;\Rightarrow\; f(x_0) = 0,
\]
e il teorema \`e dimostrato.$$
),

/*Teorema dei valori Intermedi di Bolzano, 1a forma*/
(
$$Sia $f\colon I \to \mathbb{R}$ una funzione continua definita in un intervallo $I$ (qualunque: chiuso, aperto, semiaperto, limitato o illimitato) di $\mathbb{R}$. Siano $a, b \in I$ con $f(a) < f(b)$. Allora $[f(a), f(b)] \subset f(I)$. Inoltre posto
\[
  m = \inf_I f \quad\text{e}\quad M = \sup_I f,
\]
risulta $]m, M[ \;\subset f(I)$, cio\`e $\forall\, y \in\; ]m,M[$ esiste $x \in I$ tale che $f(x) = y$.$$,
$$Teorema dei valori Intermedi di Bolzano, prima forma$$,
$$Sia $y \in\; ]f(a), f(b)[$ e definiamo $g\colon I \to \mathbb{R}$ con $g(x) = f(x) - y$. Evidentemente $g(a) = f(a) - y < 0$ e $g(b) = f(b) - y > 0$ e quindi $g(a)g(b) < 0$. Perci\`o, per il teorema degli zeri se $a < b$ esiste $x \in\; ]a,b[$ tale che $g(x) = 0$, mentre se $b < a$, esiste $x \in\; ]b,a[$ tale che $g(x) = 0$. In ogni caso esiste $x \in I$ tale che $f(x) - y = g(x) = 0$ e quindi $f(x) = y$. Proviamo la seconda parte. Sia $y \in \mathbb{R}$ con $m < y < M$. Allora per le propriet\`a dell'estremo inferiore e superiore esistono $a, b \in I$ tali che
\[
  m \leq f(a) < y < f(b) \leq M.
\]
Per quanto provato prima, si ha $y \in f(I)$ e quindi esiste $x \in I$ tale che $f(x) = y$.$$
),

/*Teorema dei valori Intermedi di Bolzano, 2a forma*/
(
$$Sia $f\colon I \to \mathbb{R}$ una funzione continua definita in un intervallo $I$ (qualunque: chiuso, aperto, semiaperto, limitato o illimitato) di $\mathbb{R}$. Siano $a, b \in I$ con $f(a) < f(b)$. Allora $[f(a), f(b)] \subset f(I)$. Inoltre posto
\[
  m = \inf_I f \quad\text{e}\quad M = \sup_I f,
\]
risulta $]m, M[ \;\subset f(I)$, cio\`e $\forall\, y \in\; ]m,M[$ esiste $x \in I$ tale che $f(x) = y$.$$,
$$Teorema dei valori Intermedi di Bolzano, seconda forma$$,
$$Sia $y \in\; ]f(a), f(b)[$ e definiamo $g\colon I \to \mathbb{R}$ con $g(x) = f(x) - y$. Evidentemente $g(a) = f(a) - y < 0$ e $g(b) = f(b) - y > 0$ e quindi $g(a)g(b) < 0$. Perci\`o, per il teorema degli zeri se $a < b$ esiste $x \in\; ]a,b[$ tale che $g(x) = 0$, mentre se $b < a$, esiste $x \in\; ]b,a[$ tale che $g(x) = 0$. In ogni caso esiste $x \in I$ tale che $f(x) - y = g(x) = 0$ e quindi $f(x) = y$. Proviamo la seconda parte. Sia $y \in \mathbb{R}$ con $m < y < M$. Allora per le propriet\`a dell'estremo inferiore e superiore esistono $a, b \in I$ tali che
\[
  m \leq f(a) < y < f(b) \leq M.
\]
Per quanto provato prima, si ha $y \in f(I)$ e quindi esiste $x \in I$ tale che $f(x) = y$.$$
),

/*Teorema di Weierstrass*/
(
$$Sia $A \subset \mathbb{R}$ un compatto di $\mathbb{R}$, cio\`e un insieme chiuso e limitato. Sia $f\colon A \to \mathbb{R}$ una funzione continua. Allora $f$ ammette minimo e massimo. In particolare $f$ \`e limitata.$$,
$$Teorema di Weierstrass$$,
$$Occupiamoci solo dell'esistenza del massimo (per il minimo si procede allo stesso modo). Sia
\[
  M = \sup_{x\in A} f(x) \in ]-\infty, +\infty] \quad\text{(esiste sempre!)}
\]
1) Costruiamo una successione $(b_n)_{n\in\mathbb{N}}$ di numeri reali tale che $b_n < M$ e $b_n \to M$. A tal fine basta porre
\[
  b_n =
  \begin{cases}
    M - \dfrac{1}{n+1} & \text{se } M < +\infty \\[4pt]
    n & \text{se } M = +\infty
  \end{cases}
\]
2) Costruiamo una successione \emph{massimizzante} per $f$, cio\`e una successione $(a_n)_{n\in\mathbb{N}}$ di elementi di $A$ tale che $f(a_n) \to M$. Possiamo procedere in questo modo. Per ogni $n \in \mathbb{N}$, dato che $b_n < M$, per la seconda propriet\`a dell'estremo superiore esiste $a_n \in A$ tale che
\[
  \underbrace{b_n}_{\uparrow M} < f(a_n) \leq M
\]
Cos\`i per il teorema dei carabinieri, si ha $f(a_n) \to M$.\\
3) La successione $(a_n)_{n\in\mathbb{N}}$ \`e una successione di elementi di $A$ e $A$ \`e compatto, perci\`o esiste una sottosuccessione $(a_{n_k})_{k\in\mathbb{N}}$ convergente a qualche elemento di $A$, cio\`e $a_{n_k} \to x_0 \in A$. Poi, essendo $f$ una funzione continua, da $a_{n_k} \to x_0 \in A$ segue che $f(a_{n_k}) \to f(x_0) \in \mathbb{R}$. Ma $(f(a_{n_k}))_{k\in\mathbb{N}}$ \`e una successione estratta da $(f(a_n))_{n\in\mathbb{N}}$ che ha per limite $M$ e quindi $f(a_{n_k}) \to M$. Perci\`o si ha
\[
  f(a_{n_k}) \to M \quad\text{e}\quad f(a_{n_k}) \to f(x_0) \quad\text{per } k \to +\infty
\]
e per l'unicit\`a del limite si conclude che $M = f(x_0)$. Allora l'estremo superiore di $f$ \`e un valore assunto dalla funzione e quindi $f$ ha massimo.$$
),

/*Carattere e somma serie Geometrica q^n (da imparare come gestire dopo che torno)*/
(
$$$$,
$$$$,
$$$$
),

/*Condizione necessaria per la convergenza di una serie*/
(
$$Sia $\sum a_n$ una serie numerica. Allora
\[
  \sum_{n=0}^{+\infty} a_n \text{ \`e convergente} \;\Rightarrow\; a_n \to 0.
\]$$,
$$Condizione necessaria per la convergenza di una serie$$,
$$Sia $(s_n)_{n\in\mathbb{N}}$ la successione delle somme parziali della serie $\sum_{n=0}^{+\infty} a_n$. Per definizione
\[
  \forall\, n \in \mathbb{N}^*\colon\; s_n = \sum_{k=0}^{n} a_k = \sum_{k=0}^{n-1} a_k + a_n = s_{n-1} + a_n
\]
e quindi $a_n = s_n - s_{n-1}$. D'altra parte, essendo la serie convergente, deve essere $\lim_n s_n = s \in \mathbb{R}$ e quindi anche $\lim_n s_{n-1} = s$. Allora, per la linearit\`a dell'operazione di limite, si ha
\[
  \lim_{n\to+\infty} a_n = \lim_{n\to+\infty} s_n - \lim_{n\to+\infty} s_{n-1} = s - s = 0,
\]
che prova la tesi.$$
),

/*Teorema di Fermat*/
(
$$Sia $f\colon A \to \mathbb{R}$ e supponiamo che $f$ sia derivabile in un punto $x_0$ interno ad $A$. Allora
\[
  x_0 \text{ \`e un punto di minimo o massimo locale per } f
  \;\Rightarrow\; f'(x_0) = 0.
\]$$,
$$Teorema di Fermat$$,
$$Per fissare le idee supponiamo che $x_0$ sia un punto di minimo locale per $f$. Allora esiste un intorno $U$ di $x_0$ tale che
\begin{equation}
  x \in U \cap A_{x_0} \;\Rightarrow\; f(x) - f(x_0) \geq 0. \label{eq:ferm4}
\end{equation}
Poi, considerando il rapporto incrementale si ha
\[
  \forall\, x \in U \cap A_{x_0}\colon\;
  \frac{f(x)-f(x_0)}{x - x_0}
  \begin{cases}
    \leq 0 & \text{se } x < x_0 \\
    \geq 0 & \text{se } x > x_0,
  \end{cases}
\]
perch\'e il numeratore \`e sempre positivo mentre il denominatore cambia segno a seconda che $x$ sia minore o maggiore di $x_0$ (si veda Figura 4 a destra). Notiamo ora che essendo $x_0$ di accumulazione a sinistra e a destra per $A$ e $f$ derivabile in $x_0$, risulta
\[
  \lim_{x \to x_0^-} \underbrace{\frac{f(x)-f(x_0)}{x-x_0}}_{\leq 0\text{ in un intorno di }x_0}
  = f'(x_0)
  \;\xRightarrow{\text{teor. di prolung. disug.}}\;
  f'(x_0) \leq 0
\]
\[
  \lim_{x \to x_0^+} \underbrace{\frac{f(x)-f(x_0)}{x-x_0}}_{\geq 0\text{ in un intorno di }x_0}
  = f'(x_0)
  \;\xRightarrow{\text{teor. di prolung. disug.}}\;
  f'(x_0) \geq 0.
\]
In definitiva si ha $f'(x_0) \leq 0$ e $f'(x_0) \geq 0$ e quindi necessariamente $f'(x_0) = 0$.$$
),

/*Teorema di Rolle*/
(
$$Sia $f\colon [a,b] \to \mathbb{R}$ continua in $[a,b]$ e derivabile in $]a,b[$. Supponiamo che $f(a) = f(b)$. Allora esiste $c \in\; ]a,b[$ tale che $f'(c) = 0$.$$,
$$Teorema di Rolle$$,
$$Per i teorema di Weierstrass, $f$ ha minimo e massimo in $[a,b]$. Quindi esistono $x_1, x_2 \in [a,b]$ tali che
\[
  \forall\, x \in [a,b]\colon\; f(x_1) \leq f(x) \leq f(x_2).
\]
Si possono presentare due casi:
\begin{enumerate}
  \item $x_1, x_2 \in \{a, b\}$. Allora, essendo $f(a) = f(b)$, si ha $f(x_1) = f(x_2)$ e quindi $f$ \`e costante su $[a,b]$. In tal caso chiaramente ogni $c \in\; ]a,b[$ soddisfa $f'(c) = 0$.
  \item almeno uno tra $x_1$ e $x_2$ appartiene a $]a,b[$. Allora per la regola di Fermat, si ha $f'(x_1) = 0$ o $f'(x_2) = 0$, a seconda che sia $x_1$ o $x_2$ ad essere interno all'intervallo $[a,b]$.
\end{enumerate}
In ogni caso si \`e provata l'esistenza di un punto $c \in\; ]a,b[$ su cui la derivata si annulla.$$
),

/*Teorema di Lagrange*/
(
$$Sia $f\colon [a,b] \to \mathbb{R}$ continua su $[a,b]$ e derivabile su $]a,b[$. Allora
\[
  \exists\, c \in\; ]a,b[\quad\text{t.c.}\quad \frac{f(b)-f(a)}{b-a} = f'(c).
\]$$,
$$Teorema di Lagrange (o del valor medio)$$,
$$La funzione affine che rappresenta il segmento congiungente i punti $(a, f(a))$ e $(b, f(b))$ ha espressione
\[
  \ell\colon [a,b] \to \mathbb{R} \qquad \ell(x) = f(a) + \frac{f(b)-f(a)}{b-a}(x-a).
\]
Notiamo che
\[
  \ell(a) = f(a) \quad\text{e}\quad \ell(b) = f(a) + (f(b)-f(a)) = f(b)
\]
e che $\ell$ \`e derivabile in $[a,b]$ risulta $\ell'(x) = (f(b)-f(a))/b-a$. Applichiamo il Teorema 2.8, di Rolle, alla funzione
\[
  g\colon [a,b] \to \mathbb{R},\quad g(x) = f(x) - \ell(x).
\]
Evidentemente $g$ \`e continua su $[a,b]$ e derivabile in $]a,b[$, perch\'e differenza di funzioni continue su $[a,b]$ e di funzioni derivabili su $]a,b[$. Inoltre, per come \`e definita $\ell$,
\[
  \begin{cases}
    g(a) = f(a) - \ell(a) = 0 \\
    g(b) = f(b) - \ell(b) = 0
  \end{cases}
\]
e perci\`o $g(a) = g(b)$. Allora, il teorema di Rolle garantisce che esiste $c \in\; ]a,b[$ tale che
\[
  0 = g'(c) = f'(c) - \ell'(c) = f'(c) - \frac{f(b)-f(a)}{b-a},
\]
da cui segue che $f'(c) = (f(b)-f(a))/(b-a)$.$$
),

/*Teorema degli accrescimenti finiti*/
(
$$Sia $I$ un intervallo di $\mathbb{R}$ e $f\colon I \to \mathbb{R}$ una funzione continua in $I$ e derivabile in $\mathring{I}$ (interno di $I$). Supponiamo che la funzione derivata $f'$ sia limitata in $\mathring{I}$, cio\`e che esista $L \geq 0$ tale che
\[
  \forall\, x \in \mathring{I}\colon\; |f'(x)| \leq L < +\infty.
\]
Allora $f$ \`e Lipschitziana su $I$ con costante di Lipschitz $L$, cio\`e
\[
  \forall\, x, y \in I\colon\quad |f(x) - f(y)| \leq L|x-y|.
\]$$,
$$Teorema degli accrescimenti finiti$$,
$$E' sufficiente provare la tesi per $x < y$. Siano quindi $x, y \in I$, con $x < y$. Allora $f|_{[x,y]}$ \`e continua in $[x,y]$ e derivabile in $]x,y[$. Perci\`o, per il teorema di Lagrange, esiste $c \in\; ]x,y[$ tale che
\[
  \frac{f(x)-f(y)}{x-y} = \frac{f(y)-f(x)}{y-x} = f'(c)
\]
e quindi, essendo chiaramente $c \in \mathring{I}$, si ha
\[
  \frac{|f(x)-f(y)|}{|x-y|} \leq |f'(c)| \leq L,
\]
da cui, moltiplicando per $|x-y|$, segue la tesi.$$
),

/*Teorema della media integrale*/
(
$$Sia $\mathcal{R}([a,b])$ e poniamo $m = \inf_{[a,b]} f$ e $M = \sup_{[a,b]} f$. Allora il valor medio di $f$ su $[a,b]$ verifica
\begin{equation}
  m \leq \frac{1}{b-a}\int_a^b f \leq M. \label{eq:med1}
\end{equation}
In particolare, se $f$ \`e continua in $[a,b]$ esiste $c \in [a,b]$ tale che
\[
  \frac{1}{b-a}\int_a^b f = f(c).
\]$$,
$$Teorema della media integrale$$,
$$Evidentemente $\forall\, x \in [a,b]$: $m \leq f(x) \leq M$. Perci\`o per la monotonia dell'integrale
\[
  m(b-a) = \int_a^b m \leq \int_a^b f \leq \int_a^b M = M(b-a)
\]
e dividendo per $b-a$ si ottiene la \eqref{eq:med1}. Supponiamo ora che $f$ sia continua su $[a,b]$. Allora per il teorema di Weierstrass $m$ e $M$ sono valori assunti dalla funzione $f$ (sono il minimo e il massimo di $f$) e dato che vale la \eqref{eq:med1}, dal teorema dei valori intermedi segue che esiste $c \in [a,b]$ tale che $f(c) = (b-a)^{-1}\int_a^b f$.$$
),

/*Primo teorema fondamentale del calcolo*/
(
$$Sia $f\colon I \to \mathbb{R}$ localmente integrabile secondo Riemann e $F\colon I \to \mathbb{R}$ una sua funzione integrale (di punto iniziale arbitrario). Allora
\begin{enumerate}[label=(\roman*)]
  \item $F$ \`e continua su $I$
  \item Se $f$ \`e continua in $I$, allora $F$ \`e derivabile in $I$ e, per ogni $x \in I$, $F'(x) = f(x)$.
\end{enumerate}$$,
$$Primo teorema fondamentale del calcolo$$,
$$Sia $x \in I$ e $h \neq 0$ tale che $x+h \in I$. Allora, ricordando che $F(y) - F(x) = \int_x^y f$ (Osservazione 2.8, della lezione precedente), si ha
\[
  \frac{F(x+h)-F(x)}{h} = \frac{1}{h}\int_x^{x+h} f.
\]
Ora, dato che $f$ \`e continua, per il teorema sulla media integrale (e Osservazione 2.6 della lezione precedente), esiste $c(h) \in I$ (che dipende da $h$), compreso tra $x$ e $x+h$, tale che
\[
  \frac{1}{h}\int_x^{x+h} f = f(c(h)),
\]
si veda Figura 6 (a destra). Allora, essendo $c(h)$ compreso tra $x$ e $x+h$, si ha $|c(h)-x| \leq |h|$, e quindi, dal teorema dei carabinieri segue che $c(h) \to x$ per $h \to 0$. Perci\`o, dato che $f$ continua in $x$ si ha $\lim_{h\to 0} f(c(h)) = f(x)$. In definitiva si ha
\[
  \lim_{h\to 0} \frac{F(x+h)-F(x)}{h} = f(x).
\]
Questo prova che $F$ \`e derivabile in $x$ e $F'(x) = f(x)$.$$
),

/*Secondo teorema fondamentale del calcolo*/
(
$$Sia $f\colon I \to \mathbb{R}$ continua e $F\colon I \to \mathbb{R}$ una primitiva di $f$. Allora
\begin{equation}
  \int_a^b f = F(b) - F(a), \label{eq:II1}
\end{equation}
per ogni $a, b \in I$. La differenza $F(b) - F(a)$ si indica anche con una delle seguenti notazioni
\[
  [F(x)]_a^b, \quad F(x)\big|_{x=a}^{x=b}, \quad o \quad F(x)\big|_a^b.
\]$$,
$$Secondo teorema fondamentale del calcolo$$,
$$Siano $a, b \in I$. Dato che $f$ \`e continua, per il primo teorema fondamentale del calcolo integrale, la funzione $G(x) = \int_a^x f$ \`e una primitiva di $f$. Allora $F$ e $G$ sono due primitive di $f$ in $I$ e la Proposizione 1.4 garantisce che esiste $c \in \mathbb{R}$ tale che
\[
  \forall\, x \in I\colon\; G(x) = F(x) + c.
\]
Allora
\[
  F(b) - F(a) = G(b) - \underbrace{G(a)}_{=0} = G(b) = \int_a^b f.
  \qedhere
\]$$
),

/*Disuguaglianza di Bernoulli*/
(
$$Sia $x \in \mathbb{R}$ con $x \geq -1$. Allora
\[
  \forall\, n \in \mathbb{N}\colon\quad (1+x)^n \geq 1 + nx,
\]
dove si fa la convenzione che $0^0 = 1$.$$,
$$Disuguaglianza di Bernoulli$$,
$$Proviamo la disuguaglianza mediante il principio di induzione. Definiamo il predicato $\mathsf{P}(n)$: $(1+x)^n \geq 1+nx$. Evidentemente $(1+x)^0 = 1 = 1+0x$ e quindi $\mathcal{P}(0)$ \`e vera.

Supponiamo che $\mathsf{P}(n)$ sia vera. Allora, moltiplicando la disuguaglianza $(1+x)^n \geq 1+nx$ per $1+x \geq 0$ e ricordando che $x^2 \geq 0$, si ha
\[
  (1+x)^{n+1} = (1+x)(1+x)^n \geq (1+x)(1+nx)
  = 1 + x + nx + nx^2 \geq 1 + (n+1)x.
\]
Quindi $\mathsf{P}(n+1)$ \`e vera. Dal Principio di induzione stabilito nel Teorema ?? si conclude allora che $\mathsf{P}(n)$ \`e vera per ogni $n \in \mathbb{N}$.$$
),

/*Caratterizazione degli insiemi contigui*/
(
$$Siano $A, B \subset \mathbb{R}$ due insiemi non vuoti di $\mathbb{R}$ e supponiamo che $A \leq B$. Allora sono equivalenti
\begin{enumerate}[label=(\roman*)]
  \item Gli insiemi $A$ e $B$ sono contigui (cio\`e $\sup A = \inf B$)
  \item $\forall\,\varepsilon > 0\;\exists\, a \in A,\;\exists\, b \in B$ tali che $b - a < \varepsilon$.
\end{enumerate}$$,
$$Caratterizzazione degli insiemi contigui$$,
$$Si noti che essendo gli insiemi $A$ e $B$ separati, allora $\sup A \leq \inf B$.
(i) $\Rightarrow$ (ii): Supponiamo che $\lambda = \sup A = \inf B$ e sia $\varepsilon > 0$. Allora per le propriet\`a dell'estremo superiore e inferiore esistono $a \in A$ e $b \in B$ tali che
\[
  a > \lambda - \frac{\varepsilon}{2} \quad\text{e}\quad b < \lambda + \frac{\varepsilon}{2}
  \;\Rightarrow\; -a < \frac{\varepsilon}{2} - \lambda \quad\text{e}\quad b < \lambda + \frac{\varepsilon}{2}
\]
e quindi sommando le disuguaglianze $b - a < \varepsilon$.
(ii) $\Rightarrow$ (i): Sia $\varepsilon > 0$. Allora per (ii), esistono $a \in A$ e $b \in B$ tali che
\[
  b - a < \varepsilon.
\]
Ora, dato che $a \leq \sup A \leq \inf B \leq b$, si ha
\[
  0 \leq \inf B - \sup A \leq b - a < \varepsilon.
\]
Perci\`o, per l'arbitrariet\`a di $\varepsilon > 0$, possiamo concludere (ricordando l'Osservazione 2.1) che $\inf B - \sup A = 0 \;\Rightarrow\; \sup A = \inf B$.$$
),

/*Teorema di unicità del limite*/
(
$$Sia $A \subset \mathbb{R}$, $f\colon A \to \mathbb{R}$ e $x_0 \in \overline{\mathbb{R}}$ un punto di accumulazione per $A$. Allora esiste al pi\`u un solo punto $\ell \in \overline{\mathbb{R}}$ tale che $\lim_{x \to x_0} f(x) = \ell$.$$,
$$Teorema di unicita del limite$$,
$$Allora, per la propriet\`a di separazione (Proposizione 1.3), esistono due intorni $V_1$ di $\ell_1$ e $V_2$ di $\ell_2$ tali che
\begin{equation}
  V_1 \cap V_2 = \varnothing. \label{eq:un2}
\end{equation}
Dato che $\lim_{x\to x_0} f(x) = \ell_1$ e $\lim_{x\to x_0} f(x) = \ell_2$, per definizione di limite, esisteranno due intorni $U_1$ e $U_2$ entrambi del punto $x_0$ tali che
\begin{equation}
  \bigl(x \in U_1 \cap A_{x_0} \Rightarrow f(x) \in V_1\bigr)
  \quad\text{e}\quad
  \bigl(x \in U_2 \cap A_{x_0} \Rightarrow f(x) \in V_2\bigr). \label{eq:un3}
\end{equation}
Ma $U := U_1 \cap U_2$ \`e un intorno di $x_0$ e $x_0$ \`e punto di accumulazione per $A$, perci\`o $U \cap A_{x_0} \neq \varnothing$. Preso allora un $x \in U \cap A_{x_0}$, si avrebbe che $x \in U_1 \cap A_{x_0}$ e $x \in U_2 \cap A_{x_0}$ e quindi per la \eqref{eq:un3}, $f(x) \in V_1 \cap V_2$. Otteniamo cos\`i una contraddizione, perch\'e si \`e provato che $V_1 \cap V_2 \neq \varnothing$, ma d'altra parte vale anche la \eqref{eq:un2}.$$
),

/*Teorema limiti unilaterali funzioni Monotone*/
(
$$Sia $A \subset \mathbb{R}$, $f\colon A \to \mathbb{R}$ crescente (risp. decrescente) e $x_0 \in \overline{\mathbb{R}}$. Allora valgono le seguenti proposizioni
\begin{enumerate}[label=(\roman*)]
  \item Se $x_0$ \`e punto di accumulazione a sinistra per $A$, allora
  \[
    \lim_{x \to x_0^-} f(x) = \sup_{\substack{x\in A \\ x < x_0}} f(x)
    \quad\left(\text{risp. } \inf_{\substack{x\in A \\ x < x_0}} f(x)\right).
  \]
  In particolare, se $x_0 = +\infty$, allora $\lim_{x\to+\infty} f(x) = \sup_A f$ (risp. $\inf_A f$).
  \item Se $x_0$ \`e punto di accumulazione a destra per $A$, allora
  \[
    \lim_{x \to x_0^+} f(x) = \inf_{\substack{x\in A \\ x > x_0}} f(x)
    \quad\left(\text{risp. } \sup_{\substack{x\in A \\ x > x_0}} f(x)\right).
  \]
  In particolare, se $x_0 = -\infty$, allora $\lim_{x\to-\infty} f(x) = \inf_A f$ (risp. $\sup_A f$).
\end{enumerate}$$,
$$Teorema limiti unilateriali funzioni monotone$$,
$$Proviamo solo la (i). L'altra si prova allo stesso modo. Supponiamo $f$ crescente e poniamo
\[
  \ell = \sup_{\substack{x\in A,\,x<x_0}} f(x) \in ]-\infty,+\infty]
  \quad\left(\text{risp. } \ell = \inf_{\substack{x\in A,\,x<x_0}} f(x) \in [-\infty,+\infty[\right).
\]
Si noti che $x_0 > -\infty$, perch\'e $x_0$ \`e di accumulazione a sinistra per $A$. Si deve provare che $\lim_{x\to x_0^-} f(x) = \ell$. Sia $V$ un intorno di $\ell$. Dato che $\ell \in \mathbb{R}$ o $\ell = +\infty$ (risp. $\ell = -\infty$), risulta che $V$ \`e del tipo $]\ell-\varepsilon, \ell+\varepsilon[$ oppure $]\beta, +\infty]$ (risp. $[-\infty, \beta[$). Indichiamo con $\lambda \in \mathbb{R}$ l'estremo sinistro (risp. destro) dell'intervallo $V$. Quindi $\lambda < \ell$ (risp. $\lambda > \ell$) e
\[
  ]\lambda, \ell] \subset V \quad\text{(risp. } [\ell,\lambda[\; \subset V).
\]
Allora, per la seconda propriet\`a dell'estremo superiore (risp. inferiore) esiste $a \in A$, con $a < x_0$ tale che $f(a) > \lambda$ (risp. $f(a) < \lambda$). Poi, dato che $f$ \`e crescente (risp. decrescente)
\[
  x \in\; ]a,x_0[\;\cap A \;\Rightarrow\; x \in A \text{ e } a < x < x_0
  \;\Rightarrow\; \lambda < f(a) \leq f(x) \leq \ell \;\Rightarrow\; f(x) \in V
\]
\[
  (\text{risp. } \ell \leq f(x) \leq f(a) < \lambda \;\Rightarrow\; f(x) \in V)
\]
Ma chiaramente l'insieme $]a,x_0[\;\cap A$ si pu\`o scrivere come $U \cap A_{x_0}^-$ con $U$ intorno di $x_0$. Perci\`o si \`e provato che esiste un intorno $U$ di $x_0$ per cui vale $x \in U \cap A_{x_0}^- \;\Rightarrow\; f(x) \in V$.$$
),

/*Teorema del punto fisso*/
(
$$Sia $g\colon [a,b] \to [a,b]$ continua. Allora esiste $x_0 \in [a,b]$ tale che $g(x_0) = x_0$.$$,
$$Teorema del punto fisso$$,
$$Consideriamo la funzione $f\colon [a,b] \to \mathbb{R}$, definita come $f(x) = g(x) - x$, per ogni $x \in [a,b]$. Per ipotesi $a \leq g(a) \leq b$ e $a \leq g(b) \leq b$ e quindi $f(a) \geq 0$ e $f(b) \leq 0$. Se $f(a) = 0$ o $f(b) = 0$ la tesi \`e ovvia. Supponiamo che $f(a) > 0$ e $f(b) < 0$. Allora per il Teorema 1.1 esiste $x_0 \in\; ]a,b[$ tale che $f(x_0) = 0$ e quindi $f(x_0) = x_0$. Si veda Figura 3.$$
),

/*Teorema continuità funzinoi composte*/
(
$$Siano $A$ e $B$ due sottoinsiemi non vuoti di $\mathbb{R}$, $f\colon A \to B$ e $g\colon B \to \mathbb{R}$. Sia $x_0 \in A$. Allora
\[
  f \text{ \`e continua in } x_0 \text{ e } g \text{ \`e continua in } f(x_0)
  \;\Rightarrow\; g \circ f \text{ \`e continua in } x_0.
\]
Perci\`o, se $f$ \`e continua e $g$ \`e continua, allora $g \circ f$ \`e continua.$$,
$$Teorema continuita funzioni composte$$,
$$Sia $W$ un intorno di $g(f(x_0))$. Dato che $g$ \`e continua in $f(x_0)$, allora esiste $V$ intorno di $f(x_0)$ tale che
\[
  y \in V \cap B \;\Rightarrow\; g(y) \in W.
\]
Adesso, dato che $f$ \`e continua in $x_0$, in corrispondenza di $V$ intorno di $f(x_0)$ esiste $U$ intorno di $x_0$ tale che
\[
  x \in U \cap A \;\Rightarrow\; f(x) \in V.
\]
Allora risulta
\[
  x \in U \cap A \;\Rightarrow\; f(x) \in V \cap B \;\Rightarrow\; g(f(x)) \in W.
\]
Quindi $g \circ f$ \`e continua in $x_0$. La seconda parte del teorema segue dalla prima ricordando che la continuit\`a in un insieme significa continuit\`a in tutti i punti dell'insieme.$$
),


/*Criterio Radice*/
(
$$Sia $\sum a_n$ una serie numerica a termini positivi e supponiamo che
\[
  \lim_{n\to+\infty} \sqrt[n]{a_n} = \ell \in [0,+\infty].
\]
Valgono le seguenti proposizioni.
\begin{enumerate}[label=(\roman*)]
  \item Se $\ell < 1$, allora la serie $\sum a_n$ \`e convergente.
  \item Se $\ell > 1$, allora la serie $\sum a_n$ \`e divergente.
  \item Se $\ell = 1$, allora la serie $\sum a_n$ pu\`o essere sia convergente che divergente.
\end{enumerate}$$,
$$Criterio della radice$$,
$$(i): Supponiamo che $\ell < 1$. Allora considerato $q$ tale che $\ell < q < 1$, per il teorema della permanenza della disuguaglianze, esiste $\nu \in \mathbb{N}$ tale che $\forall\, n \in \mathbb{N}, n > \nu$: $\sqrt[n]{a_n} < q$ e quindi
\[
  \forall\, n \in \mathbb{N}, n > \nu\colon\quad a_n \leq q^n.
\]
Quindi la serie converge, essendo definitivamente maggiorata dalla serie geometrica di ragione $q < 1$.

(ii): Supponiamo adesso che $1 < \ell$. Allora, di nuovo dal teorema della permanenza delle disuguaglianze, esiste $\nu \in \mathbb{N}$ tale che per ogni intero $n > \nu$ risulta $1 < \sqrt[n]{a_n}$, cio\`e $1 < a_n$. Si riconosce allora che, essendo $a_n > 1$ per $n > \nu$, $a_n \not\to 0$. Quindi la serie $\sum a_n$ non pu\`o convergere perch\'e $a_n$ non \`e infinitesima.

(iii): Basta notare che per le serie
\begin{equation}
  \sum_{n=1}^{+\infty} \frac{1}{n} \quad\text{e}\quad \sum_{n=1}^{+\infty} \frac{1}{n^2} \label{eq:rad5}
\end{equation}
si ha $\ell = 1$, ma abbiamo visto che la prima diverge e la seconda converge.$$
),


/*Criterio Rapporto*/
(
$$Sia $\sum_{n=0}^{+\infty} a_n$ una serie numerica a termini positivi e supponiamo che
\[
  \lim_{n\to+\infty} \frac{a_{n+1}}{a_n} = \ell \in [0,+\infty].
\]
Valgono le seguenti affermazioni.
\begin{enumerate}[label=(\roman*)]
  \item Se $\ell < 1$, allora la serie $\sum a_n$ \`e convergente.
  \item Se $\ell > 1$, allora la serie $\sum a_n$ \`e divergente.
  \item Se $\ell = 1$, allora non si pu\`o dire nulla cio\`e la serie $\sum a_n$ pu\`o essere sia convergente che divergente.
\end{enumerate}$$,
$$Criterio del rapporto$$,
$$(i): Supponiamo che $\ell < 1$. Allora preso $q > 0$ tale che $\ell < q < 1$, per il teorema della permanenza delle disuguaglianze, esiste $\nu \in \mathbb{N}$ tale che
\[
  \forall\, n \in \mathbb{N}, n > \nu\colon\quad \frac{a_{n+1}}{a_n} < q \quad\text{e quindi } a_{n+1} < qa_n.
\]
Allora per ricorsione si ha
\[
  \forall\, n \in \mathbb{N}, n > \nu\colon\;
  a_n \leq qa_{n-1} \leq q^2 a_{n-2} \leq \cdots \leq q^{n-\nu-1}a_{\nu+1}
  = q^n \frac{a_{\nu+1}}{q^{\nu+1}}.
\]
Quindi per confronto la serie $\sum a_n$ \`e convergente, essendo definitivamente maggiorata da una serie geometrica di ragione $q < 1$ (moltiplicata per una costante).

(ii): Supponiamo ora che $\ell > 1$. Allora questa volta si sceglie $q$ tale che $1 < q < \ell$ e come prima si prova che esiste $\nu \in \mathbb{N}$ tale che
\[
  \forall\, n \in \mathbb{N}, n > \nu\colon\; a_n > q^n \frac{a_{\nu+1}}{q^{\nu+1}}.
\]
Perci\`o, essendo $q > 1$, per confronto risulta $a_n \to +\infty$ e quindi la serie $\sum a_n$ non pu\`o convergere.

(iii): Le serie \eqref{eq:rad5} forniscono un caso in cui $\ell = 1$, ma una converge a l'altra diverge.$$
),


/*Criteri d'Ingtegrabilità*/
(
$$Sia $f\colon [a,b] \to \mathbb{R}$ una funzione limitata. Allora le seguenti affermazioni sono equivalenti:
\begin{enumerate}[label=(\roman*)]
  \item $f$ \`e integrabile su $[a,b]$
  \item per ogni $\varepsilon > 0$ esiste $P \in \mathcal{D}([a,b])$ tale che $S(f,P) - s(f,P) < \varepsilon$.
  \item esiste $(P_n)_{n\in\mathbb{N}}$ successione di suddivisioni di $[a,b]$ tale che $\lim_{n\to+\infty} S(f,P_n) - s(f,P_n) = 0$.
\end{enumerate}
Inoltre, se \`e vera la (iii) (e quindi sono vere anche le altre), allora
\begin{equation}
  \lim_{n\to+\infty} s(f,P_n) = \lim_{n\to+\infty} S(f,P_n) = \int_a^b f. \label{eq:int3}
\end{equation}$$,
$$Criteri d'integrabilita$$,
$$Per la caratterizzazione degli insiemi contigui richiamata nella lezione precedente e applicata agli insiemi numerici
\[
  A = \bigl\{s(f,P)\bigm| P \in \mathcal{D}([a,b])\bigr\}
  \quad\text{e}\quad
  B = \bigl\{S(f,P)\bigm| P \in \mathcal{D}([a,b])\bigr\},
\]
la (i) equivale a
\begin{equation}
  \forall\,\varepsilon > 0\;\exists\, Q, R \in \mathcal{D}([a,b]) \text{ tali che } S(f,Q) - s(f,R) < \varepsilon. \label{eq:int4}
\end{equation}
Proviamo (i) $\Rightarrow$ (ii). Sia $\varepsilon > 0$ e $Q, R \in \mathcal{D}([a,b])$ tali che $S(f,Q) - s(f,R) < \varepsilon$. Allora, posto $P = Q \cup R$, per la (2), si ha
\[
  s(f,R) \leq s(f,P) \leq S(f,P) \leq S(f,Q).
\]
Da cui segue che $S(f,P) - s(f,P) \leq S(f,Q) - s(f,R) < \varepsilon$.

(ii) $\Rightarrow$ (iii). Evidentemente per ogni $n \in \mathbb{N}$ esiste $P_n \in \mathcal{D}([a,b])$ tale che
\[
  0 \leq S(f,P_n) - s(f,P_n) < \frac{1}{n+1}.
\]
Perci\`o $\lim_{n\to+\infty} S(f,P_n) - s(f,P_n) = 0$.

(iii) $\Rightarrow$ (i). Dato che $\lim_{n\to+\infty} S(f,P_n) - s(f,P_n) = 0$, se $\varepsilon > 0$ esiste $n \in \mathbb{N}$ tale che $S(f,P_n) - s(f,P_n) < \varepsilon$ e la tesi \`e dimostrata.

Per la seconda parte dell'enunciato, supponiamo che valga la (iii). Allora, dato che $f$ \`e integrabile, per ogni $n \in \mathbb{N}$
\[
  s(f,P_n) \leq \int_a^b f \leq S(f,P_n)
\]
e quindi
\[
  0 \leq \int_a^b f - s(f,P_n) \leq S(f,P_n) - s(f,P_n)
  \quad\text{e}\quad
  0 \leq S(f,P_n) - \int_a^b f \leq S(f,P_n) - s(f,P_n).
\]
Perci\`o, dal teorema dei carabinieri si ottiene \eqref{eq:int3}.$$
),


/*Integrabilità funzioni monotone*/
(
$$Sia $f\colon [a,b] \to \mathbb{R}$ una funzione monotona (crescente o decrescente). Allora $f$ \`e limitata e integrabile secondo Riemann su $[a,b]$.$$,
$$Integrabilita funzioni monotone$$,
$$Supponiamo per fissare le idee che $f$ sia crescente. Per prima cosa osserviamo che $f$ \`e limitata. Infatti risulta
\begin{equation}
  \forall\, x \in [a,b]\colon\; f(a) \leq f(x) \leq f(b), \label{eq:mon3}
\end{equation}
e quindi $f(a)$ e $f(b)$ sono rispettivamente un minorante e un maggiorante di $f$ su $[a,b]$. Dimostriamo che $f$ \`e integrabile su $[a,b]$. Sia $P_n \in \mathcal{D}([a,b])$ la suddivisione di $[a,b]$ equispaziata con $n+1$ punti. Allora $P_n = \{a = x_0 < x_1 < \cdots < x_{n-1} < x_n = b\}$ con
\[
  x_k = a + kh \quad\text{e}\quad h = \frac{b-a}{n}.
\]
Dato che $f$ \`e crescente in $[a,b]$, per ogni $k = 1, \ldots, n$,
\[
  m_k = \inf_{I_k} f = f(x_{k-1}) \quad\text{e}\quad M_k = \sup_{I_k} f = f(x_k).
\]
Perci\`o
\begin{align*}
  S(f,P_n) - s(f,P_n)
  &= \sum_{k=1}^{n}(f(x_k) - f(x_{k-1})) \cdot h \\
  &= h \cdot (f(x_n) - f(x_0)) \\
  &= \frac{b-a}{n} \cdot (f(b) - f(a)) \to 0,
\end{align*}
dove si \`e usato il fatto che la somma $\sum_{k=1}^n (f(x_k) - f(x_{k-1}))$ \`e telescopica e quindi
\[
  \sum_{k=1}^{n}(f(x_k)-f(x_{k-1}))
  = (f(x_1)-f(x_0)) + (f(x_2)-f(x_1)) + \cdots + (f(x_n)-f(x_{n-1}))
  = f(x_n) - f(x_0).
\]
Dal teorema sui criteri di integrabilit\`a segue che $f$ \`e integrabile secondo Riemann su $[a,b]$.$$
),


/*Teorema di Heine-Cantor sull'uniforme continuità*/
(
$$Sia $f\colon A \to \mathbb{R}$. Allora
\[
  A \text{ compatto e } f \text{ continua su } A \;\Rightarrow\; f \text{ uniformemente continua su } A.
\]$$,
$$Teorema di Heine-Cantor sull'uniforme continuita$$,
$$Sia $A$ compatto e $f\colon A \to \mathbb{R}$ continua. Supponiamo per assurdo che $f$ non sia uniformemente continua. Questo significa che esiste $\varepsilon > 0$ tale che
\[
  \forall\,\delta > 0\;\exists\, x,y \in A \text{ t.c. } |x-y| < \delta \text{ e } |f(x)-f(y)| \geq \varepsilon.
\]
Allora, prendendo $\delta = 1/(n+1)$ con $n \in \mathbb{N}$, si ottengono due successioni $(x_n)_{n\in\mathbb{N}}$ e $(y_n)_{n\in\mathbb{N}}$ di elementi di $A$ tali che
\begin{equation}
  \forall\, n \in \mathbb{N}\colon\quad |x_n - y_n| < \frac{1}{n+1}
  \quad\text{e}\quad |f(x_n) - f(y_n)| \geq \varepsilon. \label{eq:hc6}
\end{equation}
Dato che $A$ \`e compatto, esiste una successione estratta $(x_{n_k})_{k\in\mathbb{N}}$ convergente ad un punto $\bar x \in A$. Inoltre, dalla prima delle \eqref{eq:hc6} segue che
\[
  \forall\, k \in \mathbb{N}\colon\quad
  \underbrace{x_{n_k} - \frac{1}{n_k+1}}_{\downarrow \bar x} < y_{n_k} < \underbrace{x_{n_k} + \frac{1}{n_k+1}}_{\downarrow \bar x}
\]
e per il teorema dei carabinieri si ha $y_{n_k} \to \bar x$ per $k \to +\infty$. Allora, usando la continuit\`a di $f$, si ottiene che
\[
  \lim_{k\to+\infty} f(x_{n_k}) - f(y_{n_k}) = f(\bar x) - f(\bar x) = 0.
\]
Questo risultato contrasta con la seconda di \eqref{eq:hc6} e quindi si otterrebbe una contraddizione. Perci\`o $f$ deve essere uniformemente continua.$$
),


/*Integrabilità continue su intervallo compatto*/
(
$$Ogni funzione continua su un intervallo chiuso e limitato $[a,b]$ \`e integrabile secondo Riemann su $[a,b]$.$$,
$$Integrabilita funzioni continue su intervallo compatto$$,
$$Sia $f\colon [a,b] \to \mathbb{R}$ una funzione continua. Per prima cosa osserviamo che, per il teorema di Weierstrass, $f$ \`e limitata (una funzione continua su un compatto ammette massimo e minimo e quindi \`e limitata). Dimostriamo ora il criterio di integrabilit\`a visto nell'Osservazione 1.3(i), cio\`e
\[
  \forall\,\varepsilon > 0\;\exists\, P = \{a = x_0 < \cdots < x_n = b\} \in \mathcal{D}([a,b])
  \text{ tale che }
  \sum_{k=1}^{m} |I_k| \cdot \omega_f(I_k) < \varepsilon.
\]
A tal fine notiamo che, essendo $f$ continua su un compatto, il teorema di Heine-Cantor garantisce che $f$ \`e uniformemente continua su $[a,b]$. Questo significa (Osservazione 1.3(ii)) che l'oscillazione della funzione sui sottointervalli di $[a,b]$ si pu\`o rendere piccola a piacere a patto di prendere la loro ampiezza abbastanza piccola. Fissiamo $\varepsilon > 0$. Si tratta di fare in modo che le oscillazioni della funzione sugli intervalli $I_k$ siano piccole abbastanza in modo da rendere la somma $(*)$ pi\`u piccola di $\varepsilon$. Allora, dato che $f$ \`e uniformemente continua, esiste $\delta > 0$ tale che
\[
  \text{per ogni sottointervallo compatto } I \subset [a,b]\colon\;
  |I| < \delta \;\Rightarrow\; \omega_f(I) \leq \frac{\varepsilon}{b-a+1}.
\]
Adesso scegliamo una suddivisione $P = \{a = x_0 < \cdots < x_n = b\}$ di $[a,b]$ in modo che
\[
  \max_{1\leq k\leq n} |I_k| < \delta, \quad\text{dove } I_k = [x_{k-1}, x_k]
\]
(si pu\`o per esempio prendere una suddivisione equispaziata con $x_k = a+kh$, $h = (b-a)/n$ e $n \in \mathbb{N}^*$ grande abbastanza in modo che $h < \delta$). Allora, per la suddivisione $P$, risulta
\[
  \sum_{k=1}^{n} |I_k|\omega_f(I_k)
  \leq \frac{\varepsilon}{b-a+1}\sum_{k=1}^{n} |I_k|
  = \frac{\varepsilon}{b-a+1}(b-a) < \varepsilon.
\]
In definitiva si \`e provato il criterio (2) e perci\`o la funzione $f$ \`e integrabile su $[a,b]$.$$
);


/* Parte riguardante gli indovinelli matematici adesso! */
/* Proverò a metterne circa un 50ina, in modo da non rendere il gioco ripetitivo in questo caso dato che non aiuterebbe di certo*/
/* FONTE DI QUESTI QUIZ: https://www.atuttodonna.it/indovinelli-matematici-e-logici/ */
drop table if exists  quiz_list; 


create table quiz_list(
	id BIGINT generated by default as identity primary key,
  question text,
  answer text
); 

insert into quiz_list(question, answer)
values 
(
$$ Puoi usare quattro nove per renderlo uguale a 100? $$,
$$  99+9/9 = 100 $$
),

(
$$ Ho quattro volte l’età di mia figlia. Tra 20 anni avrò il doppio di lei. Quanti anni abbiamo adesso? $$,
$$  Ho 40 anni e mia figlia 10 $$
),

(
$$ C’è un albero con due rami. In entrambi stanno appollaiati degli uccellini. Indovina quanti uccellini ci sono nel ramo di sopra e in quello di sotto sapendo che se uno degli uccelli scende, quelli di sotto diventano il doppio di quelli di sopra e se uno degli uccelli sale, diventano pari. $$,
$$  Gli uccelli sopra sono 5 e sotto sono 7 $$
),

(
$$ Ci sono diversi libri su una libreria. Se un libro è il 4° da sinistra e il 6° da destra, quanti libri ci sono sullo scaffale? $$,
$$ 9 libri. $$
),

(
$$ Due persone davanti a due persone, due persone dietro a due persone e due persone accanto a due persone. Quante persone ci sono? $$,
$$ Quattro $$
),

(
$$ La somma dell’età di 5 uomini è 121. Tra 20 anni quale sarà la somma della loro età? $$,
$$  221 anni. 20x5 + 121 = 221 $$ 
),

(
$$ Marco ha due cestini identici. Il primo è riempito con 1 kg di sassi, il secondo con 1 kg di piume. Quale dei due cestini è il più pesante? $$,
$$  Pesano entrambi un chilo $$
),

(
$$ Padre e figlio hanno 36 anni in 2. Sapendo che il padre ha 30 anni più del figlio, quanti anni ha il figlio? $$,
$$  Il figlio ha 3 anni e il padre 33 $$
),

(
$$ Un certo numero ha tre cifre. La somma delle tre cifre equivale a 36 volte questo numero. Sette volte la cifra di sinistra più 9 è uguale a 5 volte la somma delle altre due cifre. 8 volte la seconda cifra meno 9 è uguale alla somma della prima e della terza. Qual è il numero? $$,
$$ 324 $$
),

(
$$ Qual è il numero che, diviso per la sua metà, dà il suo doppio? $$,
$$  Il numero 1. 1/0,5 = 2 $$
),


/* 11esimo quiz */
(
$$ Provate a trovare 3 numeri (interi e positivi) che sommati tra di loro o che moltiplicati tra di loro diano lo stesso risultato. $$,
$$  1, 2 e 3 $$
),

(
$$ 1 1 1 = 9. Quali sono i segni che mancano? $$,
$$  (1+1+1)² = 9  $$
),

(
$$ Se 5 gatti catturano 5 topi in 5 minuti, quanti gatti ci vogliono per catturare 100 topi in 100 minuti? $$,
$$ Sempre 5 gatti $$
),

(
$$ Se 1=5, 2=7000, 3=60596 e 4=652387. 5 è uguale a cosa? $$,
$$  A 1 perché 1=5 quindi 5=1 $$
),

(
$$ Ogni giorno raddoppio la quantità di vino in una botte. Se in 5 giorni riempo la botte, quanto tempo ci metto a riempirne la metà? $$,
$$  4 giorni. Raddoppiando ogni giorno, il penultimo giorno la botte sarà piena per metà $$
),

(
$$ Un artigiano deve fare 100 targhe numeriche, dalla 1 alla 100. Quante volte dovrà scrivere il numero 9? $$,
$$ 20: 9 19 29 39 49 59 69 79 89 90 91 92 93 94 95 96 97 98 99 $$
),

(
$$ L’altro ieri, Marco aveva 17 anni; l’anno prossimo ne avrà 20. Come è possibile? $$,
$$ Ieri era il 31 dicembre e Marco ha compiuto 18 anni. Quest’anno ne compierà 19 e il prossimo 20 $$
),

(
$$ Un mattone pesa un chilo più mezzo mattone. Quanto pesa il mattone? $$,
$$ 2 chili $$
),

(
$$ Due anatre depongono 3 uova in 3 minuti. Considera questa come la massima velocità possibile; quante anatre saranno necessarie per ottenere 300 uova in 300 minuti? $$,
$$ 2 anatre $$
),

(
$$ È il reciproco di 9 moltiplicato per 2 e il prodotto di 9 per 9. Qual è il numero? $$,
$$ 81 $$
),


/* 21esimo indovinello */
(
$$ Hai 26 calzini bianchi, 18 calzini neri, 16 calzini blu, tutti sparsi sul pavimento e la stanza è buia. Quanti calzini devi raccogliere e portare fuori per essere sicuro di averne almeno un paio appaiati nel colore? $$,
$$  4: se i primi tre sono tutti spaiati, il quarto sarà il compagno di uno degli altri $$
),

(
$$ Su un autobus ci sono 7 passeggeri. Quante persone ci sono su quell’autobus? $$,
$$  8. Bisogna aggiungere l’autista $$
),

(
$$ Se dico che un cerchio ha 2 lati, puoi indicare i lati? $$,
$$ Dentro e fuori $$
),

(
$$ Massimo ha una famiglia davvero numerosa. Ha 10 zie, 10 zii e 30 cugini. Ogni cugino ha una zia che non è la zia Massimo. Com’è possibile? $$,
$$ La loro zia è la madre di Massimo $$
),

(
$$ È un poligono con 3 lati e 3 vertici. $$,
$$ Triangolo $$
),

(
$$ Una persona molto povera non riusciva a rinunciare al vizio del fumo. Non avendo però abbastanza soldi per permettersi di acquistare le sigarette raccoglieva i mozziconi e riusciva costruirsi con cinque di essi una sigaretta. Sfruttando questo espediente, un giorno riuscì a fumare cinque sigarette. Quanti mozziconi ha dovuto raccogliere per poter costruire le cinque sigarette e quanti gliene sono avanzati? $$,
$$ Ha dovuto raccogliere 21 mozziconi, avanzandone uno. Infatti, fumando una sigaretta si ottiene sempre un mozzicone. Quindi dopo aver raccolto cinque mozziconi per la prima sigaretta, per quelle successive gliene basta raccogliere solo quattro perché ha potuto riciclare quello ottenuto fumando la sigaretta precedente. Il mozzicone dell’ultima sigaretta è quello che avanza $$
),

(
$$ Il contachilometri di Marco segna 3233 Km. A quale chilometro segnerà nuovamente un numero con 3 (cifre uguali? $$,
$$ 3303 Km $$
),

(
$$ Lucia e Bruno vanno al Luna Park e di fronte al gioco del tiro a segno fanno una scommessa: per ogni bersaglio colpito da Lucia, Bruno gli paga 4 euro, mentre per quelli mancati, lui deve pagare 5 euro a Bruno. Se dopo 12 colpi Lucia ha in tasca 12 euro, quanti bersagli non è riuscito di colpire? $$,
$$ 4 $$
),

(
$$ Teresa e Marta hanno la stessa quantità di denaro. Quanto deve dare Teresa a Marta affinché Marta abbia 100 in più di lei? $$,
$$ 50 euro $$
),

(
$$ Una ninfea cade in un lago. Ogni giorno raddoppia la sua superficie e in 100 giorni copre tutta la superficie del lago. Quanti giorni ha impiegato per coprire la metà del lago? $$,
$$ 99 $$
),


/* 31esimo indovinello */
(
$$ Qual è il termine successivo nella successione “1 – 11 – 21 – 1211 – 111221” ? $$,
$$ Il termine successivo è 312211. Ogni termine si ricava dal precedente “spiegando cosa è scritto”: in 1112211 ci sono tre 1, due 2 e ancora due 1, quindi 3 1, 2 2, 2 1 $$
),

(
$$ Un plotone di soldati è composto da 3 colonne e 15 righe. Le righe sono distanti tra loro di 2 metri. Quanto è lungo il plotone? $$,
$$ 28 metri $$
),

(
$$ In un’aia vi sono conigli e polli; ma in tutto sono 100 zampe e 40 ceste. Quanti conigli e quanti polli sono? $$,
$$ 10 i conigli e 30 polli $$
),

(
$$ Un assassino è condannato a morte. Deve scegliere tra tre stanze. La prima è in fiamme, la seconda è piena di assassini con le pistole cariche e la terza è pieno di leoni che non mangiano da 3 anni. Quale stanza è più sicura per lui? $$,
$$ La terza stanza, perché quei leoni non mangiano da tre anni, quindi sono morti $$
),

(
$$ Un uomo ha 53 calzini nel suo cassetto: 21 identici blu, 15 identici neri e 17 identici rossi. Le luci sono spente e lui è completamente al buio. Quanti calzini deve prendere per essere sicuro al 100% di avere almeno un paio di calzini neri? $$,
$$ 40 calzini. Se tira fuori 38 calzini (sommando i due maggiori, 21 e 17), anche se è molto improbabile, è possibile che siano tutti blu e rossi. Per essere sicuro al 100% di avere anche un paio di calzini neri, deve tirarne fuori altri due $$
),

(
$$ Sei a un bivio in cui una direzione porta alla Città delle Bugie (dove tutti mentono sempre) e l’altra alla Città della Verità (dove tutti dicono sempre la verità). C’è una persona al bivio che vive in una delle città, ma non sei sicuro di quale. Quale domanda potresti fare alla persona per scoprire quale strada porta alla Città della Verità? $$,
$$ “In quale direzione vivi?” Qualcuno della Città della Menzogna mentirà e indicherà la Città della Verità; qualcuno della Città della Verità direbbe la verità e indicherà anche la Città della Verità $$
),

(
$$ Un uomo vive da solo al trentesimo piano di un grattacielo. Va sempre in ufficio alla stessa ora e ritorna a casa alla medesima ora. Quando deve scendere utilizza sempre l’ascensore, mentre quando, finito l’orario lavorativo, ritorna a casa, utilizza l’ascensore solo per salire fino al decimo piano, e sale i restanti piani a piedi. Perché? $$,
$$ È troppo basso per poter schiacciare il pulsante del trentesimo piano $$
),

(
$$ Può andare su e giù ma non può muoversi. Aiuta le persone a decidere come vestirsi. Aiuta anche a tenere sotto controllo la salute delle persone. Che cos’è? $$,
$$ Temperatura $$
),

(
$$ Una ragazza incontra un leone e un unicorno nella foresta. Il leone mente ogni lunedì, martedì e mercoledì e gli altri giorni dice la verità. L’unicorno mente il giovedì, il venerdì e il sabato e gli altri giorni della settimana dice la verità. “Ieri mentivo”, disse il leone alla ragazza. “Anch’io”, disse l’unicorno. Che giorno è? $$,
$$ Giovedì. L’unico giorno in cui entrambi dicono la verità è la domenica; ma oggi non può essere domenica perché il leone dice la verità anche il sabato (ieri). Giorno dopo giorno, l’unico giorno in cui uno di loro mente e uno di loro dice la verità con quelle due affermazioni è giovedì $$
),

(
$$ Sta appesa alla parete anche senza chiodi. $$,
$$ Crepa $$
),


/* 41esimo indovinello */
(
$$ Una ragazza sola in una stanza buia ha un fiammifero in mano. Nella stanza ci sono anche una candela, una lampada a olio e un camino. Cosa accende per primo? $$,
$$ Il fiammifero $$
),

(
$$ Ci sono tre persone (Alex, Ben e Cody), uno dei quali è un cavaliere, uno un furfante e uno una spia. Il cavaliere dice sempre la verità, il furfante mente sempre e la spia può mentire o dire la verità. Alex dice: “Cody è un furfante”. Ben dice: “Alex è un cavaliere”. Cody dice: “Io sono la spia”. Chi è il cavaliere, chi il furfante e chi la spia? $$,
$$ Sappiamo che Ben non sta dicendo la verità perché se lo fosse, ci sarebbero due cavalieri; quindi Ben potrebbe essere il furfante o la spia. Anche Cody non può essere il cavaliere, perché allora la sua affermazione sarebbe una bugia. Quindi questo deve significare che Alex è il cavaliere. Ben, quindi, deve essere la spia, poiché la spia a volte dice la verità; lasciando Cody come il furfante $$
),

(
$$ Ho 4 sorelle e ognuna di loro ha un fratello. Quanti fratelli ho? $$,
$$ Le tue sorelle hanno un unico fratello, cioè te. Quindi tu non hai nessun fratello $$
),

(
$$ È mezzogiorno ma il cielo è scuro e piove tantissimo. Pensi che tra 60 ore il sole splenderà nuovamente? $$,
$$ No, perché dopo 60 ore sarà mezzanotte e ovviamente non ci sarà il sole $$
),

(
$$ Se cinque gatti possono catturare cinque topi in cinque minuti, quanto tempo impiegherà un gatto a catturare un topo? $$,
$$ Cinque minuti. Utilizzando le informazioni che conosciamo, un gatto impiegherebbe 25 minuti per catturare tutti e cinque i topi (5×5=25). Quindi lavorando all’indietro e dividendo 25 per cinque, otteniamo cinque minuti per un gatto per catturare ogni topo $$
),

(
$$ Non è il giorno che segue la domenica, non è il giovedì, non è quello che precede il mercoledì. Sabato non è né domani, né ieri, né due giorni prima di ieri. Di che giorno si tratta? $$,
$$ Sabato $$
),

(
$$ Sui Pirenei, proprio al confine tra Spagna e Francia cade un aereo a causa di un’avaria al motore: dove vengono sepolti i superstiti? $$,
$$ I superstiti non possono essere sepolti perché sono vivi $$
),

(
$$ C’è una botte senza coperchio e del vino dentro. “Questa botte di vino è piena più della metà”, dice la donna. “No, non lo è”, dice l’uomo. “È pieno meno della metà.” Senza strumenti di misurazione e senza rimuovere il vino dalla botte, come possono determinare facilmente chi ha ragione? $$,
$$ Inclina la botte finché il vino non tocca appena il bordo della botte. Se il fondo della canna è visibile, significa che è pieno meno della metà. Se il fondo della botte è ancora completamente coperto dal vino, allora è pieno per più della metà $$
),

(
$$ Più persone mi custodiscono e meno sono al sicuro. Cosa sono? $$,
$$ Un segreto $$
),

(
$$ Ci sono tre borse, ciascuna contenente due biglie. Il sacchetto A contiene due biglie bianche, il sacchetto B contiene due biglie nere e il sacchetto C contiene una biglia bianca e una biglia nera. Scegli un sacchetto a caso ed estrai una biglia, che è bianca. Qual è la probabilità che anche la biglia rimanente dello stesso sacchetto sia bianca? $$,
$$ 2 su 3. Sai di non avere il sacchetto B. Ma poiché il sacchetto A ha due biglie bianche, avresti potuto scegliere qualsiasi biglia; se pensi a quattro biglie in totale dai sacchetti A e C, tre bianche e una nera, avrai maggiori possibilità di scegliere un’altra biglia bianca $$
);



/* Parte riguardante le formule */
/* Provero a mettere circa una 30ina delle formule piu famose ed importanti presenti in matematica */
drop table if exists formulas_list; 


create table formulas_list(
	id BIGINT generated by default as identity primary key,
  formula text,
  answer text
); 

insert into formulas_list(formula, answer)
values
(
  $$ $E = mc^2$ $$,
  $$ L'equivalenza massa-energia $$
),

(
  $$\begin{cases}
      \rho \left( \frac{\partial \mathbf{u}}{\partial t} + \mathbf{u} \cdot \nabla \mathbf{u} \right) = -\nabla p + \mu \nabla^2 \mathbf{u} + \mathbf{f} \\
      \nabla \cdot \mathbf{u} = 0
    \end{cases} $$,
  $$ Le equazioni di Navier-Stokes $$
),

(
  $$ \[ N = R^* \cdot f_p \cdot n_e \cdot f_l \cdot f_i \cdot f_c \cdot L \] $$,
  $$ L'equazione di Drake $$
),

(
  $$ \[ \Delta x \cdot \Delta p \geq \frac{\hbar}{2} \] $$,
  $$ Il principio di indeterminazione $$
),

(
  $$ \[P(A|B) = \frac{P(B|A)P(A)}{P(B)}\] $$,
  $$ Formula di Bayes $$
),

(
  $$ Q = \frac{\pi r^4 \Delta p}{8 \eta L} $$,
  $$ La legge di Poiseuille $$
),

(
  $$ \zeta(s) = 0 \implies \Re(s) = \frac{1}{2} $$,
  $$ L'ipotesi di Riemann $$
),

(
  $$ x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a} $$,
  $$ L'equazione di secondo grado $$
),

(
  $$ \left[ \mu \frac{\partial}{\partial \mu} + \beta(g) \frac{\partial}{\partial g} + \gamma(g) m \frac{\partial}{\partial m} + n \gamma(g) \right] \Gamma^{(n)} = 0 $$,
  $$ L'equazione di Callan-Symanzik $$
),

(
  $$ \mathcal{L} = -\frac{1}{4} F_{\mu\nu} F^{\mu\nu} + i \bar{\psi} \gamma^\mu D_\mu \psi + |D_\mu \phi|^2 - V(\phi) + \bar{\psi}_i y_{ij} \psi_j \phi + h.c. $$,
  $$ Il Modello standard $$
),


/* 11esimo formula */
(
  $$ In un qualunque poliedro semplice, il numero delle facce più il numero dei vertici meno il numero degli spigoli dà sempre come risultato 2 $$,
  $$ La formula di Eulero per i poliedri $$
),

(
  $$ R_{\mu\nu} - \frac{1}{2}Rg_{\mu\nu} + \Lambda g_{\mu\nu} = \frac{8\pi G}{c^4} T_{\mu\nu} $$,
  $$ La relatività generale $$
),

(
  $$ a^n + b^n = c^n \quad \text{per } n > 2 \text{ e } a, b, c \in \mathbb{Z}^+ $$,
  $$ L'ultimo teorema di Fermat $$
),

(
  $$ \begin{cases} \nabla \cdot \mathbf{E} = \frac{\rho}{\varepsilon_0} \\ \nabla \cdot \mathbf{B} = 0 \\ \nabla \times \mathbf{E} = -\frac{\partial \mathbf{B}}{\partial t} \\ \nabla \times \mathbf{B} = \mu_0 \left( \mathbf{J} + \varepsilon_0 \frac{\partial \mathbf{E}}{\partial t} \right) \end{cases} $$,
  $$ Le legi di Maxwell $$
),

(
  $$ f(x) = \frac{1}{\sigma \sqrt{2\pi}} e^{-\frac{1}{2}\left(\frac{x-\mu}{\sigma}\right)^2} $$,
  $$ La distribuzione normale $$
),

(
  $$ \frac{\partial V}{\partial t} + \frac{1}{2}\sigma^2 S^2 \frac{\partial^2 V}{\partial S^2} + rS \frac{\partial V}{\partial S} - rV = 0 $$,
  $$ Il modello di Black-Scholes $$
),

(
  $$ x_{n+1} = r x_n (1 - x_n) $$,
  $$ La teoria del caos $$
),

(
  $$ F = G \frac{m_1 m_2}{r^2} $$,
  $$ La legge di gravitazione universale $$
),

(
  $$ i\hbar \frac{\partial}{\partial t} \Psi(\mathbf{r},t) = \left[ -\frac{\hbar^2}{2m}\nabla^2 + V(\mathbf{r},t) \right] \Psi(\mathbf{r},t) $$,
  $$ L'equazione di Schrödinger $$
),

(
  $$ \hat{f}(\xi) = \int_{-\infty}^{\infty} f(x) e^{-2\pi i x \xi} \, dx $$,
  $$ La trasformata di Fourier $$
),


/* 21esima formula*/
(
  $$ \Delta S_{\text{universo}} \geq 0 $$,
  $$ Il secondo principio della termodinamica $$
),

(
  $$ \partial_\mu j^\mu = 0 $$,
  $$ Il teorema di Noether $$
),

(
  $$ \begin{cases} t' = \gamma \left( t - \frac{v x}{c^2} \right) \\ x' = \gamma (x - v t) \\ y' = y \\ z' = z \end{cases} $$,
  $$ Le trasformazioni di Lorentz $$
),

(
  $$ a^2 + b^2 = c^2 $$,
  $$ Il teorema di Pitagora $$
),

(
  $$ \max_{1 \leq n \leq N} \left| \sum_{k=1}^n x_{k d} \right| \geq C $$,
  $$ La discrepanza di Erdős $$
),

(
  $$ e^{i\pi} + 1 = 0 $$,
  $$ L'identità di Eulero $$
),

(
  $$ \int_a^b f(x) \, dx = F(b) - F(a) $$,
  $$ Il Teorema Fondamentale del Calcolo $$
),

(
  $$ R_{\mu\nu} - \frac{1}{2} R g_{\mu\nu} + \Lambda g_{\mu\nu} = \frac{8\pi G}{c^4} T_{\mu\nu} $$,
  $$ L'equazione di Campo di Einstein $$
),

(
  $$ f'(x) = \lim_{h \to 0} \frac{f(x+h) - f(x)}{h} $$,
  $$ La formula delle derivate $$
),

(
  $$ \frac{\partial^2 u}{\partial t^2} = c^2 \nabla^2 u $$,
  $$ Equazione delle onde $$
);
